# テンソル≒ndarray

In [1]:
%matplotlib inline
import matplotlib
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data) # 形状とデータ型（整数）を引き継ぐ
x_rand = torch.rand_like(x_data, dtype=torch.float) # 形状のみを引き継ぐ
x_ones
x_rand

tensor([[0.5154, 0.0386],
        [0.5299, 0.8545]])

In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [9]:
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.6174, 0.9573, 0.6899],
        [0.8131, 0.8142, 0.6142]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
